FROM ubuntu:18.04
RUN apt -y update && \
    apt -y upgrade && \
    apt -qq -y install libsm6 libxext6 libxrender-dev
RUN apt -y update && apt install -y python3 python3-pip
RUN pip3 install opencv-python numpy
RUN pip3 install psutil

RUN pip3 install matplotlib
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt-get -y install python3-tk

RUN pip3 install --upgrade pip
RUN pip3 install tensorflow==2.0.0