FROM ubuntu:18.04
RUN apt -y update && \
    apt -y upgrade && \
    apt -qq -y install libsm6 libxext6 libxrender-dev
RUN apt -y update && apt install -y python3 python3-pip
RUN pip3 install opencv-python numpy

